
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import IsnadRegistryContractArtifactJson from '../../../contracts/isnad_registry/target/isnad_registry-IsnadRegistry.json' with { type: 'json' };
export const IsnadRegistryContractArtifact = loadContractArtifact(IsnadRegistryContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract IsnadRegistry;
 */
export class IsnadRegistryContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, IsnadRegistryContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): IsnadRegistryContract {
    return Contract.at(address, IsnadRegistryContract.artifact, wallet) as IsnadRegistryContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<IsnadRegistryContract>(PublicKeys.default(), wallet, IsnadRegistryContractArtifact, (instance, wallet) => IsnadRegistryContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<IsnadRegistryContract>(publicKeys, wallet, IsnadRegistryContractArtifact, (instance, wallet) => IsnadRegistryContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof IsnadRegistryContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<IsnadRegistryContract['methods'][M]>
  ) {
    return new DeployMethod<IsnadRegistryContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      IsnadRegistryContractArtifact,
      (instance, wallet) => IsnadRegistryContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return IsnadRegistryContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(IsnadRegistryContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'trust_scores' | 'attestation_counts' | 'attestations' | 'attest_claims' | 'credentials'> {
      return {
        trust_scores: {
      slot: new Fr(1n),
    },
attestation_counts: {
      slot: new Fr(2n),
    },
attestations: {
      slot: new Fr(3n),
    },
attest_claims: {
      slot: new Fr(4n),
    },
credentials: {
      slot: new Fr(5n),
    }
      } as ContractStorageLayout<'trust_scores' | 'attestation_counts' | 'attestations' | 'attest_claims' | 'credentials'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** attest(skill_hash: field, quality: integer) */
    attest: ((skill_hash: FieldLike, quality: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor() */
    constructor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** delete_credential(key_id: field) */
    delete_credential: ((key_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_attestation_count(skill_hash: field) */
    get_attestation_count: ((skill_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_credential(owner: struct, key_id: field) */
    get_credential: ((owner: AztecAddressLike, key_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_credential_for_skill(owner: struct, key_id: field, authwit_nonce: field) */
    get_credential_for_skill: ((owner: AztecAddressLike, key_id: FieldLike, authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_trust_score(skill_hash: field) */
    get_trust_score: ((skill_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** revoke_attestation(skill_hash: field) */
    revoke_attestation: ((skill_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** rotate_credential(key_id: field, new_value: array, label: field) */
    rotate_credential: ((key_id: FieldLike, new_value: FieldLike[], label: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** store_credential(key_id: field, value: array, label: field) */
    store_credential: ((key_id: FieldLike, value: FieldLike[], label: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
