/**
 * deploy.mjs — Deploy IsnadRegistry v0.3.0 to the local Aztec network
 *
 * Prerequisites:
 *   - aztec start --local-network running at localhost:8080
 *
 * Usage (run from sdk/ directory):
 *   node scripts/deploy.mjs
 *
 * Output:
 *   - Prints the deployed contract address
 *   - Writes ../../scripts/deployment-info.json
 *   - Writes ../../frontend/.env.local
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, '../..');
const SDK_ROOT = resolve(__dirname, '..');

// Aztec packages (from sdk/node_modules)
import { EmbeddedWallet } from '@aztec/wallets/embedded';
import { registerInitialLocalNetworkAccountsInWallet } from '@aztec/wallets/testing';
import { AztecAddress } from '@aztec/stdlib/aztec-address';
import { SponsoredFeePaymentMethod } from '@aztec/aztec.js/fee';
import { Fr } from '@aztec/foundation/curves/bn254';
import { loadContractArtifact } from '@aztec/stdlib/abi';
import { getContractInstanceFromInstantiationParams } from '@aztec/stdlib/contract';
import { SPONSORED_FPC_SALT } from '@aztec/constants';

// IsnadRegistry contract (from compiled dist)
import { IsnadRegistryContract } from '../dist/index.js';

const PXE_URL = 'http://localhost:8080';
// SponsoredFPC artifact path in the global aztec installation
const SPONSORED_FPC_ARTIFACT_PATH =
  '/home/ec2-user/.aztec/current/node_modules/@aztec/noir-contracts.js/artifacts/sponsored_fpc_contract-SponsoredFPC.json';

async function deploy() {
  console.log('═══════════════════════════════════════════════');
  console.log('  IsnadRegistry v0.3.0 — Deployment');
  console.log('═══════════════════════════════════════════════\n');
  console.log(`Connecting to ${PXE_URL}...`);

  // 1. Create embedded wallet (ephemeral PXE + node connection)
  const wallet = await EmbeddedWallet.create(PXE_URL, { ephemeral: true });
  console.log('Connected.');

  // 2. Register pre-deployed test accounts into the wallet
  console.log('Registering test accounts...');
  const addresses = await registerInitialLocalNetworkAccountsInWallet(wallet);
  const adminAddress = addresses[0];
  console.log(`Admin (test account 0): ${adminAddress}\n`);

  // 3. Register SponsoredFPC with the wallet so PXE can simulate fee payment
  console.log('Registering SponsoredFPC...');
  const fpcArtifactJson = JSON.parse(readFileSync(SPONSORED_FPC_ARTIFACT_PATH, 'utf8'));
  const fpcArtifact = loadContractArtifact(fpcArtifactJson);
  const fpcInstance = await getContractInstanceFromInstantiationParams(fpcArtifact, {
    salt: new Fr(SPONSORED_FPC_SALT),
  });
  await wallet.registerContract(fpcInstance, fpcArtifact);
  console.log(`SponsoredFPC: ${fpcInstance.address}\n`);
  const paymentMethod = new SponsoredFeePaymentMethod(fpcInstance.address);

  // 4. Deploy IsnadRegistry
  console.log('Deploying IsnadRegistry...');
  console.log('(ZK proof generation: 30-120s)');

  const contract = await IsnadRegistryContract.deploy(wallet, adminAddress)
    .send({
      from: adminAddress,
      fee: { paymentMethod },
      wait: { timeout: 300_000 },
    });

  const contractAddress = contract.address.toString();

  console.log('\n✓ Deployed!');
  console.log(`  Address: ${contractAddress}\n`);

  // 5. Write deployment-info.json
  const deploymentInfo = {
    network: 'local',
    contractAddress,
    deployerAddress: adminAddress.toString(),
    pxeUrl: PXE_URL,
    deployedAt: new Date().toISOString(),
    aztecVersion: '4.0.0-devnet.2-patch.0',
    contractVersion: '0.3.0',
    sponsoredFPC: fpcInstance.address.toString(),
    testAccounts: {
      test0: { address: adminAddress.toString() },
    },
  };

  const deployInfoPath = resolve(PROJECT_ROOT, 'scripts/deployment-info.json');
  writeFileSync(deployInfoPath, JSON.stringify(deploymentInfo, null, 2));
  console.log(`✓ Wrote ${deployInfoPath}`);

  // 6. Write frontend/.env.local
  const envContent = [
    `# Generated by scripts/deploy.mjs`,
    `# IsnadRegistry v0.3.0 deployed to local Aztec network`,
    `# ${new Date().toISOString()}`,
    ``,
    `NEXT_PUBLIC_USE_MOCK=false`,
    `NEXT_PUBLIC_PXE_URL=${PXE_URL}`,
    `NEXT_PUBLIC_CONTRACT_ADDRESS=${contractAddress}`,
    ``,
  ].join('\n');

  const envPath = resolve(PROJECT_ROOT, 'frontend/.env.local');
  writeFileSync(envPath, envContent);
  console.log(`✓ Wrote ${envPath}`);

  console.log('\n═══════════════════════════════════════════════');
  console.log('  Done. Start the frontend:');
  console.log('    cd frontend && npm run dev');
  console.log('═══════════════════════════════════════════════\n');

  return contractAddress;
}

deploy().catch(err => {
  console.error('\nDeployment failed:', err.message);
  if (err.stack) console.error(err.stack);
  process.exit(1);
});
